### ISSUE TITLE
Fountainhead stopped working when updating to latest version of Sublime Text 

### ISSUE THREAD

**Issue by forthrin** [derickc/Fountainhead#13]
Sublime Text 3 was updated yesterday to build 3103. After this, Fountainhead stopped working. The following error message occur in my console. How can this be fixed?

    no such context .lyrics in Packages/Fountainhead/Fountainhead.tmLanguage
    error: Error loading syntax file "Packages/Fountainhead/Fountainhead.tmLanguage": Error in regex: unmatched close parenthesis in regex )

**Comment by derickc** [comment]
Pushed new changes that fix the Regex issue with help from Manuel. 

You can download the new .tmLanguage file which has the fix.

If you used Package Control, it should update soon and automatically update.

**Comment by anatomatic** [comment]
Thank you! Nice to have Fountainhead back in action.
