### ISSUE TITLE
Doesn't work properly with non-Latin text

### ISSUE THREAD

**Issue by gelav** [derickc/Fountainhead#20]
Seems like when writing in Cyrillic characters autocomplete function doesn't work.

**Comment by derickc** [comment]
I will look into it.  Should just the characters in the wikipedia page be supported, or is there a better reference? https://en.wikipedia.org/wiki/Cyrillic_alphabets

**Comment by gelav** [comment]
@derickc http://symbolcodes.tlt.psu.edu/bylanguage/cyrchart.html here Russian alphabet with the most common extensions.
When I writing the dialogue in Cyrillic Fountainhead doesn't recognize it and I must force a character element by preceding it with the @ every time, which is a hassle.

**Comment by derickc** [comment]
Thanks for the website. I am currently researching a solution and will try to have something within the next couple of days.

**Comment by derickc** [comment]
@gelav I added Cyrillic character support. I tried to test as best I could, but if you find any issues, let me know.

**Comment by gelav** [comment]
@derickc Thank you very much for your effort!
