### ISSUE TITLE
Change color of action/dialogue

### ISSUE THREAD

**Issue by asterox** [derickc/Fountainhead#25]
Hi there.
First off, thanks for this! I'm monkeying around with sublime and with atom and trying to land on which I'll use most and your package may be swinging things.

I was wondering if there was a way to specify a different color for actions vs dialogue? Thanks very much!

**Comment by derickc** [comment]
The easiest would probably to copy an existing [color scheme](https://github.com/derickc/Fountainhead/tree/master/schemes) and save a new version with the color changes you want. From there you can enter the file path to it in your user preferences.
